version: '3'

services:
  router1:
    build:
      context: ./routers/router1
    container_name: router1
    hostname: router1
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.10
      external:
        ipv4_address: 172.20.0.20
    volumes:
      - ./routers/router1/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  router2:
    build:
      context: ./routers/router2
    container_name: router2
    hostname: router2
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.20
      segment1:
        ipv4_address: 120.0.16.10
    volumes:
      - ./routers/router2/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  router3:
    build:
      context: ./routers/router3
    container_name: router3
    hostname: router3
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.30
      segment2:
        ipv4_address: 120.0.24.10
    volumes:
      - ./routers/router3/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

networks:
  as_internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_multicast: "true"
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
  segment1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "120.0.16.0/24"
  segment2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "120.0.24.0/24"
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"