services:
  router1:
    image: router_image:2.0.0
    container_name: router1
    hostname: router1
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.10
      external:
        ipv4_address: 120.0.80.5
    volumes:
      - ./routers/router1/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  router2:

    image: router_image:2.0.0
    container_name: router2
    hostname: router2
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.20
      entreprise:
        ipv4_address: 120.0.16.10
    volumes:
      - ./routers/router2/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  router3:
    image: router_image:2.0.0
    container_name: router3
    hostname: router3
    privileged: true
    networks:
      as_internal:
        ipv4_address: 10.0.1.30
      particulier:
        ipv4_address: 120.0.24.10
    volumes:
      - ./routers/router3/frr:/etc/frr
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  dhcp-server:
    image: dhcp_image:1.0.0
    container_name: dhcp-server
    hostname: dhcp-server
    restart: unless-stopped
    privileged: true
    networks:
      - temp_net
    volumes:
      - ./dhcp/data:/var/lib/dhcp
      - ./dhcp/config:/etc/dhcp
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    
    # We'll manually connect to particulier network after creation

networks:
  temp_net:
    driver: bridge
    internal: true  # This prevents internet access
  as_internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_multicast: "true"
    ipam:
      config:
        - subnet: 10.0.1.0/24
  entreprise:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 120.0.16.0/24
  particulier:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 120.0.24.0/24
  external:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 120.0.80.4/30
          gateway: 120.0.80.6


# networks:
#   temp_net:
#     driver: bridge
#     internal: true  # This prevents internet access
#   as_internal:
#     driver: macvlan
#     driver_opts:
#       parent: dummy0
#     ipam:
#       config:
#         - subnet: 10.0.1.0/24
#   entreprise:
#     driver: macvlan
#     driver_opts:
#       parent: dummy0
#     ipam:
#       config:
#         - subnet: 120.0.16.0/24
#   particulier:
#     driver: macvlan
#     driver_opts:
#       parent: dummy0
#     ipam:
#       config:
#         - subnet: 120.0.24.0/24
#   external:
#     driver: macvlan
#     driver_opts:
#       parent: dummy0
#     ipam:
#       config:
#         - subnet: 172.20.0.0/24